# Generated by Django 4.1 on 2022-11-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0002_shop_shop_ischihu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_content", models.TextField(verbose_name="评论内容")),
                ("publish_time", models.DateField(auto_now=True, verbose_name="发表时间")),
                ("reply_count", models.IntegerField(verbose_name="回帖数量")),
                ("like_count", models.IntegerField(verbose_name="点赞数量")),
                ("shop_score", models.IntegerField(verbose_name="评论给店铺的分数")),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.shop"
                    ),
                ),
            ],
            options={
                "verbose_name": "评论表",
                "verbose_name_plural": "评论表",
                "db_table": "Comments",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, verbose_name="用户名")),
                ("user_account", models.CharField(max_length=15, verbose_name=" 用户账号")),
                ("user_pwd", models.CharField(max_length=30, verbose_name="用户密码")),
                (
                    "user_profile_photo",
                    models.ImageField(upload_to="photos/", verbose_name="用户头像"),
                ),
                (
                    "is_chihu",
                    models.BooleanField(default=False, verbose_name="# 是否是吃乎作者"),
                ),
            ],
            options={
                "verbose_name": "用户表",
                "verbose_name_plural": "用户表",
                "db_table": "Users",
            },
        ),
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/", verbose_name="评论的图片")),
                (
                    "comment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="square.comment"
                    ),
                ),
            ],
            options={
                "verbose_name": "图片表",
                "verbose_name_plural": "图片表",
                "db_table": "Photos",
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="square.user"
            ),
        ),
    ]
