# Generated by Django 4.1 on 2022-11-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("square", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_profile_photo",
            field=models.ImageField(
                null=True, upload_to="photos/", verbose_name="用户头像"
            ),
        ),
    ]
