# Generated by Django 4.1 on 2022-11-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("square", "0002_alter_user_user_profile_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="shop_id", new_name="shop",
        ),
        migrations.RenameField(
            model_name="comment", old_name="user_id", new_name="user",
        ),
    ]
