# Generated by Django 4.1 on 2022-11-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("square", "0003_rename_shop_id_comment_shop_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photos", old_name="comment_id", new_name="comment",
        ),
    ]
