# Generated by Django 4.1 on 2022-11-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=20, verbose_name="店铺名称")),
                (
                    "shop_profile_photo",
                    models.ImageField(null=True, upload_to="photos", verbose_name="图片"),
                ),
                ("shop_score", models.IntegerField(default=0, verbose_name="店铺评分")),
                ("comment_count", models.IntegerField(default=0, verbose_name="评论量")),
                ("is_delete", models.BooleanField(default=False, verbose_name="逻辑删除")),
            ],
            options={
                "verbose_name": "店铺",
                "verbose_name_plural": "店铺",
                "db_table": "Shops",
            },
        ),
    ]
