# Generated by Django 4.1 on 2022-11-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_isChiHu",
            field=models.BooleanField(default=False, verbose_name="是否吃乎认证"),
        ),
    ]
