# Generated by Django 4.1.3 on 2022-11-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chihu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "db_table": "tb_comment",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=20, verbose_name="店铺名称")),
                (
                    "shop_profile_photo",
                    models.ImageField(null=True, upload_to="photos", verbose_name="图片"),
                ),
                ("shop_score", models.IntegerField(default=0, verbose_name="店铺评分")),
                ("comment_count", models.IntegerField(default=0, verbose_name="评论量")),
                (
                    "shop_isChiHu",
                    models.BooleanField(default=False, verbose_name="是否吃乎认证"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="逻辑删除")),
            ],
            options={
                "verbose_name": "店铺",
                "verbose_name_plural": "店铺",
                "db_table": "db_shop",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.IntegerField(default=0, null=True)),
                ("user_name", models.CharField(max_length=20)),
                ("password", models.IntegerField(default=0, null=True)),
                ("image", models.ImageField(null=True, upload_to="")),
                ("is_ch", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "tb_user",
            },
        ),
        migrations.CreateModel(
            name="Huitie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论回帖",
                "verbose_name_plural": "评论回帖",
                "db_table": "tb_huitie",
            },
        ),
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
                "db_table": "tb_collect",
            },
        ),
    ]
