# Generated by Django 4.1 on 2022-12-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="collect", table="Collects",),
        migrations.AlterModelTable(name="comment", table="Comments",),
        migrations.AlterModelTable(name="huitie", table="Huitie",),
        migrations.AlterModelTable(name="shop", table="Shops",),
        migrations.AlterModelTable(name="user", table="Users",),
    ]
