# Generated by Django 4.1 on 2022-11-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True, upload_to="photos/", verbose_name="用户头像"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_ch",
            field=models.BooleanField(default=False, verbose_name="# 是否是吃乎作者"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=30, verbose_name="用户密码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="sid",
            field=models.CharField(default="", max_length=15, verbose_name=" 用户账号"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(default="", max_length=20, verbose_name="用户名"),
        ),
    ]
