# Generated by Django 4.1 on 2022-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photohuitie",
            name="photos",
            field=models.ImageField(
                null=True, upload_to="photos_huitie", verbose_name="图片"
            ),
        ),
        migrations.AlterField(
            model_name="photos",
            name="image",
            field=models.ImageField(upload_to="photos_comments", verbose_name="评论的图片"),
        ),
        migrations.AlterModelTable(name="collect", table="Collects",),
        migrations.AlterModelTable(name="comment", table="Comments",),
        migrations.AlterModelTable(name="huitie", table="Huitie",),
        migrations.AlterModelTable(name="shop", table="Shops",),
        migrations.AlterModelTable(name="user", table="Users",),
    ]
