# Generated by Django 4.1 on 2023-02-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="time_renzheng",
            field=models.DateTimeField(auto_now=True, verbose_name="吃乎认证时间"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="# 是否是管理员"),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True, upload_to="photos_user/", verbose_name="用户头像"
            ),
        ),
    ]
