# Generated by Django 4.1.3 on 2022-11-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comment",
            table="db_comment",
        ),
    ]
