# Generated by Django 4.1.3 on 2022-11-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_comment_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="chihu",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
