# Generated by Django 4.1.3 on 2022-11-29 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_alter_comment_options_comment_comment_content_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comment",
            table="db_comment",
        ),
    ]
