# Generated by Django 4.1.3 on 2022-11-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0006_alter_comment_publish_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="publish_time",
            field=models.DateField(auto_now=True, verbose_name="发表时间"),
        ),
    ]
