# Generated by Django 4.1.3 on 2022-11-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0008_alter_comment_publish_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="publish_time",
        ),
    ]
